services:
  - type: worker
    name: telegram-store-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python Main_QR_PAYMENT_ALL_FIXED.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
