import { HostedBot, ApprovalRuleSet } from '../types';

export function generateTelethonProjectFiles(bot: HostedBot) {
  const { name, botUsername, apiId, apiHash, botToken, adminChatId, downloadPath, rules } = bot;

  const allowedExtsStr = rules.allowedExtensions.map(e => `'${e.toLowerCase()}'`).join(', ');
  const allowedMimesStr = rules.allowedMimeTypes.map(m => `'${m}'`).join(', ');
  const allowedKeywordsStr = rules.allowedKeywords.map(k => `'${k.toLowerCase()}'`).join(', ');
  const trustedUsersStr = rules.trustedUsernames.map(u => `'${u.replace('@', '').toLowerCase()}'`).join(', ');

  const configPy = `# ==============================================================================
# TELETHON BOT CONFIGURATION
# Bot Name: ${name} (@${botUsername || 'your_bot'})
# Generated by TeleHost AI Studio
# ==============================================================================

import os
from dotenv import load_dotenv

load_dotenv()

# Telegram API Credentials (Get from https://my.telegram.org)
API_ID = int(os.getenv("TELEGRAM_API_ID", "${apiId || '1234567'}"))
API_HASH = os.getenv("TELEGRAM_API_HASH", "${apiHash || 'your_api_hash_here'}")
BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "${botToken || '123456789:ABCdefGHIjklMNOpqrsTUVwxyZ'}")

# Admin Chat or Channel ID for approval notifications
ADMIN_CHAT_ID = int(os.getenv("ADMIN_CHAT_ID", "${adminChatId || '-100123456789'}"))

# Local Storage Directory for Auto-Downloaded Files
DOWNLOAD_DIR = os.getenv("DOWNLOAD_DIR", "${downloadPath || './downloads'}")

# Auto-Approval Rule Parameters
MAX_FILE_SIZE_MB = ${rules.maxFileSizeMB || 50}
ALLOWED_EXTENSIONS = [${allowedExtsStr || "'.pdf', '.zip', '.mp4', '.mkv', '.apk'"}]
ALLOWED_MIME_TYPES = [${allowedMimesStr || "'application/pdf', 'video/mp4', 'application/zip'"}]

# Channel Membership Verification Rule
REQUIRE_CHANNEL_MEMBERSHIP = ${rules.requireChannelMembership ? 'True' : 'False'}
CHANNEL_USERNAME = "${rules.channelUsername || '@MyChannel'}"

# Caption / Keyword Verification
REQUIRE_CAPTION_KEYWORD = ${rules.requireCaptionKeyword ? 'True' : 'False'}
ALLOWED_KEYWORDS = [${allowedKeywordsStr || "'#approved', 'download', 'submit'"}]

# User Trust Rules
AUTO_APPROVE_TRUSTED_USERS = ${rules.autoApproveTrustedUsers ? 'True' : 'False'}
TRUSTED_USERNAMES = [${trustedUsersStr || "'admin_user'"}]

# Fallback Settings
ADMIN_APPROVAL_FOR_UNKNOWN = ${rules.adminApprovalForUnknownUsers ? 'True' : 'False'}
AUTO_REJECT_EXECUTABLES = ${rules.autoRejectExecutables ? 'True' : 'False'}
CUSTOM_REJECTION_MSG = "${rules.customRejectionMessage.replace(/"/g, '\\"') || 'File rejected by automated download rule.'}"

# Webhook Dispatch Option
DISPATCH_TO_WEBHOOK = ${rules.dispatchToWebhook ? 'True' : 'False'}
WEBHOOK_URL = "${rules.webhookUrl || ''}"
`;

  const mainPy = `# ==============================================================================
# TELETHON AUTOMATED FILE DOWNLOADER WITH APPROVAL LOGIC
# Engine: Telethon (Python Telegram Client API)
# Bot Name: ${name}
# ==============================================================================

import os
import sys
import time
import logging
import asyncio
from datetime import datetime
import requests

from telethon import TelegramClient, events, Button
from telethon.tl.functions.channels import GetParticipantRequest
from telethon.tl.types import ChannelParticipant, ChannelParticipantSelf, ChannelParticipantAdmin, ChannelParticipantCreator
from telethon.errors import UserNotParticipantError, ChannelInvalidError

import config

# Configure logging format
logging.basicConfig(
    format='[%(asctime)s] [%(levelname)s] [%(name)s]: %(message)s',
    level=logging.INFO
)
logger = logging.getLogger("TeleHostBot")

# Ensure download directory exists
os.makedirs(config.DOWNLOAD_DIR, exist_ok=True)

# Initialize Telethon Telegram Client
client = TelegramClient('telehost_session', config.API_ID, config.API_HASH)

# Pending approval memory cache {msg_id: file_metadata}
pending_approvals = {}

def get_file_extension(filename):
    if not filename:
        return ""
    _, ext = os.path.splitext(filename)
    return ext.lower()

async def check_channel_membership(user_id):
    """Verify if sender is a member of required Telegram channel using Telethon"""
    if not config.REQUIRE_CHANNEL_MEMBERSHIP or not config.CHANNEL_USERNAME:
        return True
    try:
        participant = await client(GetParticipantRequest(
            channel=config.CHANNEL_USERNAME,
            participant=user_id
        ))
        logger.info(f"User {user_id} membership verified in {config.CHANNEL_USERNAME}")
        return True
    except UserNotParticipantError:
        logger.warning(f"User {user_id} is NOT a participant of {config.CHANNEL_USERNAME}")
        return False
    except Exception as e:
        logger.error(f"Error checking channel membership for {user_id}: {e}")
        # Default to True on API error to avoid softlock, or customize
        return False

async def evaluate_approval_rules(event, media_type, filename, mime_type, file_size_bytes, caption):
    """
    Evaluates automated approval logic for incoming media file.
    Returns: (status: str ['APPROVED', 'REJECTED', 'PENDING_ADMIN'], reason: str)
    """
    sender = await event.get_sender()
    sender_id = sender.id if sender else 0
    sender_username = (sender.username or "").lower() if sender else ""
    file_size_mb = file_size_bytes / (1024 * 1024)
    ext = get_file_extension(filename)

    logger.info(f"Evaluating file: '{filename}' ({file_size_mb:.2f} MB) from @{sender_username} ({sender_id})")

    # Rule 1: Auto-Reject Executable Files if configured
    if config.AUTO_REJECT_EXECUTABLES and ext in ['.exe', '.bat', '.cmd', '.scr', '.vbs', '.sh', '.msi']:
        return ('REJECTED', f"Executable files ({ext}) are prohibited for security.")

    # Rule 2: Trusted Users Bypass
    if config.AUTO_APPROVE_TRUSTED_USERS and sender_username in config.TRUSTED_USERNAMES:
        return ('APPROVED', f"Auto-approved: User @{sender_username} is in trusted whitelist.")

    # Rule 3: Channel Membership Verification
    if config.REQUIRE_CHANNEL_MEMBERSHIP:
        is_member = await check_channel_membership(sender_id)
        if not is_member:
            return ('REJECTED', f"You must join {config.CHANNEL_USERNAME} to send files for automatic processing.")

    # Rule 4: File Size Check
    if file_size_mb > config.MAX_FILE_SIZE_MB:
        if config.ADMIN_APPROVAL_FOR_UNKNOWN:
            return ('PENDING_ADMIN', f"File size ({file_size_mb:.1f} MB) exceeds limit ({config.MAX_FILE_SIZE_MB} MB). Sent for admin review.")
        else:
            return ('REJECTED', f"File size ({file_size_mb:.1f} MB) exceeds maximum allowed limit ({config.MAX_FILE_SIZE_MB} MB).")

    # Rule 5: Extension / MIME Type Check
    if config.ALLOWED_EXTENSIONS and ext and ext not in config.ALLOWED_EXTENSIONS:
        if config.ADMIN_APPROVAL_FOR_UNKNOWN:
            return ('PENDING_ADMIN', f"Extension '{ext}' not auto-approved. Sent for admin review.")
        else:
            return ('REJECTED', f"Extension '{ext}' is not in allowed extensions list: {', '.join(config.ALLOWED_EXTENSIONS)}")

    # Rule 6: Caption Keyword Check
    if config.REQUIRE_CAPTION_KEYWORD:
        caption_lower = (caption or "").lower()
        matched = any(kw in caption_lower for kw in config.ALLOWED_KEYWORDS)
        if not matched:
            return ('REJECTED', f"Caption missing required keyword from: {', '.join(config.ALLOWED_KEYWORDS)}")

    return ('APPROVED', "Passed all automated approval criteria.")

async def perform_file_download(event, media_type, filename, status_msg=None):
    """Download approved media using Telethon download_media with progress callback"""
    start_time = time.time()
    last_update_time = [start_time]

    timestamp_prefix = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_filename = filename if filename else f"media_{timestamp_prefix}"
    target_path = os.path.join(config.DOWNLOAD_DIR, f"{timestamp_prefix}_{safe_filename}")

    async def progress_callback(current, total):
        now = time.time()
        # Throttle progress updates to once every 2 seconds
        if now - last_update_time[0] >= 2.0 or current == total:
            last_update_time[0] = now
            percent = (current / total) * 100
            speed_kb = (current / 1024) / max(now - start_time, 0.1)
            logger.info(f"Downloading {safe_filename}: {percent:.1f}% ({current/1024/1024:.2f}/{total/1024/1024:.2f} MB) @ {speed_kb:.1f} KB/s")
            if status_msg:
                try:
                    await status_msg.edit(
                        f"⬇️ **Downloading File...**\\n"
                        f"📁 \`{safe_filename}\`\\n"
                        f"📊 **Progress:** \`{percent:.1f}%\` ({current/1024/1024:.1f}/{total/1024/1024:.1f} MB)\\n"
                        f"⚡ **Speed:** \`{speed_kb:.1f} KB/s\`"
                    )
                except Exception:
                    pass

    try:
        logger.info(f"Starting Telethon download to {target_path}")
        downloaded_file = await client.download_media(
            event.message.media,
            file=target_path,
            progress_callback=progress_callback
        )
        elapsed = time.time() - start_time
        logger.info(f"✅ Download completed successfully in {elapsed:.2f}s: {downloaded_file}")

        if status_msg:
            await status_msg.edit(
                f"✅ **Download & Processing Complete!**\\n"
                f"📁 Saved as: \`{os.path.basename(downloaded_file)}\`\\n"
                f"⏱️ Time taken: \`{elapsed:.2f} seconds\`"
            )

        # Send Webhook Notification if enabled
        if config.DISPATCH_TO_WEBHOOK and config.WEBHOOK_URL:
            try:
                payload = {
                    "event": "FILE_DOWNLOADED",
                    "filename": safe_filename,
                    "saved_path": target_path,
                    "sender_id": event.sender_id,
                    "download_time_seconds": round(elapsed, 2)
                }
                requests.post(config.WEBHOOK_URL, json=payload, timeout=5)
                logger.info("Webhook notification sent successfully.")
            except Exception as e:
                logger.error(f"Webhook dispatch error: {e}")

        return target_path

    except Exception as e:
        logger.error(f"Error during Telethon download_media: {e}", exc_info=True)
        if status_msg:
            await status_msg.edit(f"❌ **Download Failed:** {str(e)}")
        return None

# ==============================================================================
# TELETHON TELEGRAM EVENT HANDLERS
# ==============================================================================

@client.on(events.NewMessage)
async def handle_incoming_message(event):
    """Handle all incoming messages containing media files"""
    if not event.media or not event.is_private:
        if event.text and event.text.startswith('/start'):
            await event.respond(
                f"👋 **Welcome to {config.CUSTOM_REJECTION_MSG} Telethon File Downloader Bot!**\\n\\n"
                f"Send me any document, video, zip archive, or audio file.\\n"
                f"I will automatically evaluate approval rules and process your download!"
            )
        return

    # Extract media metadata from Telethon message
    media = event.media
    filename = "file"
    mime_type = "application/octet-stream"
    file_size_bytes = 0
    media_type = "document"

    if hasattr(media, 'document') and media.document:
        doc = media.document
        file_size_bytes = doc.size
        mime_type = doc.mime_type or "application/octet-stream"
        for attr in doc.attributes:
            if hasattr(attr, 'file_name') and attr.file_name:
                filename = attr.file_name
    elif hasattr(media, 'photo') and media.photo:
        filename = f"photo_{event.id}.jpg"
        mime_type = "image/jpeg"
        media_type = "photo"
        file_size_bytes = 1024 * 500  # approximate

    caption = event.text or ""
    sender = await event.get_sender()
    sender_name = sender.first_name if sender else "User"

    # Evaluate approval status
    status, reason = await evaluate_approval_rules(
        event, media_type, filename, mime_type, file_size_bytes, caption
    )

    if status == 'APPROVED':
        status_msg = await event.respond(
            f"✅ **File Auto-Approved!**\\n"
            f"📝 Reason: _{reason}_\\n"
            f"🚀 Initiating Telethon download..."
        )
        await perform_file_download(event, media_type, filename, status_msg)

    elif status == 'REJECTED':
        await event.respond(
            f"❌ **Submission Rejected**\\n\\n"
            f"⚠️ Reason: _{reason}_\\n\\n"
            f"{config.CUSTOM_REJECTION_MSG}"
        )

    elif status == 'PENDING_ADMIN':
        ack_msg = await event.respond(
            f"⏳ **Pending Admin Approval**\\n\\n"
            f"Your file \`{filename}\` requires manual admin review.\\n"
            f"Reason: _{reason}_\\n"
            f"You will be notified once reviewed."
        )

        # Notify Admin Chat with Telethon Inline Buttons
        if config.ADMIN_CHAT_ID:
            admin_text = (
                f"🔔 **New File Approval Request**\\n\\n"
                f"👤 **Sender:** {sender_name} (@{sender.username or 'none'}) [\`{event.sender_id}\`]\\n"
                f"📁 **Filename:** \`{filename}\`\\n"
                f"📦 **Size:** \`{file_size_bytes/(1024*1024):.2f} MB\`\\n"
                f"📄 **MIME:** \`{mime_type}\`\\n"
                f"💬 **Caption:** {caption or '_None_'}\\n"
                f"⚠️ **Pending Reason:** {reason}"
            )

            # Telethon inline keyboard buttons
            buttons = [
                [
                    Button.inline("Approve & Download ✅", data=f"appr_{event.id}_{event.sender_id}"),
                    Button.inline("Reject ❌", data=f"rejc_{event.id}_{event.sender_id}")
                ]
            ]

            # Cache message in pending
            pending_approvals[f"{event.id}_{event.sender_id}"] = {
                "event": event,
                "filename": filename,
                "media_type": media_type,
                "user_ack_msg": ack_msg
            }

            try:
                await client.send_message(config.ADMIN_CHAT_ID, admin_text, buttons=buttons)
            except Exception as e:
                logger.error(f"Failed to send admin notification: {e}")

@client.on(events.CallbackQuery)
async def handle_admin_callback(event):
    """Handle Admin Inline Keyboard Button Clicks"""
    data = event.data.decode('utf-8')
    admin_user = await event.get_sender()

    if data.startswith("appr_") or data.startswith("rejc_"):
        parts = data.split("_")
        action = parts[0]
        key = f"{parts[1]}_{parts[2]}"

        if key not in pending_approvals:
            await event.answer("⚠️ Approval request expired or already processed.", alert=True)
            return

        item = pending_approvals.pop(key)
        orig_event = item["event"]
        filename = item["filename"]
        media_type = item["media_type"]
        user_ack_msg = item["user_ack_msg"]

        if action == "appr":
            await event.edit(f"✅ **Approved by Admin (@{admin_user.username or admin_user.id})**\\n📁 \`{filename}\` is downloading now.")
            await user_ack_msg.edit(f"🎉 **Good news!** Admin approved your file \`{filename}\`. Downloading now...")
            await perform_file_download(orig_event, media_type, filename, status_msg=user_ack_msg)
            await event.answer("Approved and downloading!")

        elif action == "rejc":
            await event.edit(f"❌ **Rejected by Admin (@{admin_user.username or admin_user.id})**")
            await user_ack_msg.edit(f"❌ **Request Rejected:** An admin declined your file \`{filename}\`.")
            await event.answer("Request rejected.")

async def main():
    logger.info("=========================================================")
    logger.info("Starting TeleHost Telethon Auto-Downloader Bot Engine")
    logger.info(f"Bot Username Target: @{config.BOT_USERNAME if hasattr(config, 'BOT_USERNAME') else 'TelethonBot'}")
    logger.info(f"Download Directory: {os.path.abspath(config.DOWNLOAD_DIR)}")
    logger.info("=========================================================")

    # Start Telethon bot client
    await client.start(bot_token=config.BOT_TOKEN)
    me = await client.get_me()
    logger.info(f"Logged in as Telegram Bot: @{me.username} ({me.id})")
    logger.info("Telethon bot event loop is active. Listening for incoming files...")
    await client.run_until_disconnected()

if __name__ == '__main__':
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        logger.info("Bot execution terminated by user.")
`;

  const requirementsTxt = `telethon>=1.34.0
python-dotenv>=1.0.0
requests>=2.31.0
aiohttp>=3.9.0
pillow>=10.2.0
cryptg>=0.4.0
`;

  const dockerfile = `# TeleHost Telethon Bot Container Setup
FROM python:3.11-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \\
    build-essential \\
    libffi-dev \\
    && rm -rf /var/lib/apt/get/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Create downloads directory
RUN mkdir -p downloads

# Run the Telethon bot
CMD ["python", "main.py"]
`;

  const systemdService = `[Unit]
Description=TeleHost Telethon Auto Downloader Bot
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/opt/${bot.id || 'telethon_bot'}
ExecStart=/usr/bin/python3 main.py
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
`;

  const readmeMd = `# ${name} - Telethon Telegram Auto-Downloader Bot

Generated by **TeleHost AI Studio** for automated file downloads with customizable approval logic using the **Telethon** Python library.

---

## 📋 Requirements
- **Python 3.10+**
- Telegram **API ID** & **API Hash** (Get from [my.telegram.org](https://my.telegram.org))
- Telegram **Bot Token** (Get from [@BotFather](https://t.me/BotFather))

---

## 🚀 Quick Setup Guide

### 1. Install Dependencies
\`\`\`bash
pip install -r requirements.txt
\`\`\`

### 2. Configure Environment Variables
Create or edit your \`.env\` file in the project root:

\`\`\`env
TELEGRAM_API_ID=${apiId || '1234567'}
TELEGRAM_API_HASH=${apiHash || 'your_api_hash_here'}
TELEGRAM_BOT_TOKEN=${botToken || '123456789:ABCdefGHIjklMNOpqrsTUVwxyZ'}
ADMIN_CHAT_ID=${adminChatId || '-100123456789'}
DOWNLOAD_DIR=${downloadPath || './downloads'}
\`\`\`

---

## 🏃 Running the Bot

### Option A: Direct Python Execution
\`\`\`bash
python main.py
\`\`\`

### Option B: Run with Docker Container
\`\`\`bash
docker build -t telethon-bot .
docker run -d --name my-telethon-bot -v $(pwd)/downloads:/app/downloads --env-file .env telethon-bot
\`\`\`

---

## 🛡️ Configured Approval Rules
- **Max File Size:** \`${rules.maxFileSizeMB} MB\`
- **Allowed Extensions:** \`${rules.allowedExtensions.join(', ')}\`
- **Require Channel Join:** \`${rules.requireChannelMembership ? 'YES (' + rules.channelUsername + ')' : 'NO'}\`
- **Caption Keywords:** \`${rules.requireCaptionKeyword ? rules.allowedKeywords.join(', ') : 'None Required'}\`
- **Auto-Reject Executables:** \`${rules.autoRejectExecutables ? 'YES' : 'NO'}\`
`;

  return {
    mainPy,
    configPy,
    requirementsTxt,
    dockerfile,
    systemdService,
    readmeMd,
    summary: `Complete Telethon Python project for ${name} with automatic file download & approval logic.`
  };
}
